In [1]:
import simpandas as spd
from simpandas import SimDataFrame, SimSeries

units dictionary loaded from cache...
units network loaded from cache...

In [2]:
spd.__version__

'0.83.14'

In [3]:
sample_prod = spd.read_excel('./test/_testing_data/sample_prod.xlsx')
sample_prod

D:\git\simpandas\src\simpandas\readers\xlsx.py:80: FutureWarning: the 'mangle_dupe_cols' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'mangle_dupe_cols'
  excelread = pandas.read_excel(io, sheet_name=sheet_name, header=header, names=names, index_col=index_col, usecols=usecols, dtype=dtype, engine=engine, converters=converters, true_values=true_values, false_values=false_values, skiprows=skiprows, nrows=nrows, na_values=na_values, keep_default_na=keep_default_na, na_filter=na_filter, verbose=verbose, parse_dates=parse_dates, date_parser=date_parser, thousands=thousands, comment=comment, skipfooter=skipfooter, mangle_dupe_cols=mangle_dupe_cols, storage_options=storage_options)  # convert_float=convert_float, decimal=decimal

,DATE,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,date,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
0,2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
1,2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2,2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
3,2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
4,2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228
...,...,...,...,...,...,...,...
361,2106-12-03,389.264791,6782.302094,854.665589,91.398966,433.506733,227.178007
362,2106-12-10,386.549452,7096.137397,850.487971,90.952206,433.911970,227.130305
363,2106-12-17,383.853055,7443.580545,846.330773,90.507630,434.315018,227.082613
364,2106-12-24,381.175466,7830.322069,842.193896,90.065228,434.715890,227.034930
365,2106-12-31,378.516555,8263.413916,838.077240,89.624988,435.114595,226.987258

In [4]:
sample_prod.set_index('DATE')

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228
...,...,...,...,...,...,...
2106-12-03,389.264791,6782.302094,854.665589,91.398966,433.506733,227.178007
2106-12-10,386.549452,7096.137397,850.487971,90.952206,433.911970,227.130305
2106-12-17,383.853055,7443.580545,846.330773,90.507630,434.315018,227.082613
2106-12-24,381.175466,7830.322069,842.193896,90.065228,434.715890,227.034930
2106-12-31,378.516555,8263.413916,838.077240,89.624988,435.114595,226.987258

In [5]:
sample_prod.set_index('DATE', inplace=True)

In [6]:
sample_prod.index.units

'date'

# agrupación temporal
**index _must_ be datetime**

## .daily()

In [7]:
sample_prod.daily()

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228
...,...,...,...,...,...,...
2106-12-03,389.264791,6782.302094,854.665589,91.398966,433.506733,227.178007
2106-12-10,386.549452,7096.137397,850.487971,90.952206,433.911970,227.130305
2106-12-17,383.853055,7443.580545,846.330773,90.507630,434.315018,227.082613
2106-12-24,381.175466,7830.322069,842.193896,90.065228,434.715890,227.034930
2106-12-31,378.516555,8263.413916,838.077240,89.624988,435.114595,226.987258

## .monthly()

In [8]:
sample_prod.monthly()

ValueError: This SimDataFrame has multiple columns, item parameter must be provided.

ValueError: This SimDataFrame has multiple columns, item parameter must be provided.

## .yearly()

In [9]:
sample_prod.yearly()

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
YEAR,,,,,,
2100,4084.629255,286.516370,4424.965940,473.211178,62.636817,243.736822
2101,2827.851038,722.344020,3420.913611,365.836615,169.202915,241.064336
2102,1965.048786,1012.729855,2651.452633,283.549532,250.133287,238.446234
2103,1365.495099,1245.090190,2055.065361,219.771160,312.198137,235.856566
2104,948.870521,1510.798159,1592.822585,170.338362,359.695564,233.295024
2105,659.361770,2007.256589,1234.551385,132.024409,395.944791,230.761302
2106,456.681516,4112.786245,954.624300,102.088670,423.728074,228.231176

# get [ ]
## a single column name
### as SimSeries

In [10]:
single_column = sample_prod['WOPR:P1']
single_column

DATE
2100-01-01    4872.000000
2100-01-08    4838.015086
2100-01-15    4804.267236
2100-01-22    4770.754795
2100-01-29    4737.476123
                 ...
2106-12-03     389.264791
2106-12-10     386.549452
2106-12-17     383.853055
2106-12-24     381.175466
2106-12-31     378.516555
Name: WOPR:P1, Length: 366, dtype: float64, units: stb/day

### as SimDataFrame

In [11]:
sample_prod[['WOPR:P1']]

                WOPR:P1
                stb/day
DATE
2100-01-01  4872.000000
2100-01-08  4838.015086
2100-01-15  4804.267236
2100-01-22  4770.754795
2100-01-29  4737.476123
...                 ...
2106-12-03   389.264791
2106-12-10   386.549452
2106-12-17   383.853055
2106-12-24   381.175466
2106-12-31   378.516555

[366 rows x 1 columns]

## several columns by name

In [12]:
sample_prod[['WOPR:P1', 'WOPR:P2']]

                WOPR:P1     WOPR:P2
                stb/day     sm3/day
DATE
2100-01-01  4872.000000  536.000000
2100-01-08  4838.015086  533.380024
2100-01-15  4804.267236  530.772855
2100-01-22  4770.754795  528.178429
2100-01-29  4737.476123  525.596686
...                 ...         ...
2106-12-03   389.264791   91.398966
2106-12-10   386.549452   90.952206
2106-12-17   383.853055   90.507630
2106-12-24   381.175466   90.065228
2106-12-31   378.516555   89.624988

[366 rows x 2 columns]

In [13]:
sample_prod['WOPR:P1', 'WOPR:P2']

                WOPR:P1     WOPR:P2
                stb/day     sm3/day
DATE
2100-01-01  4872.000000  536.000000
2100-01-08  4838.015086  533.380024
2100-01-15  4804.267236  530.772855
2100-01-22  4770.754795  528.178429
2100-01-29  4737.476123  525.596686
...                 ...         ...
2106-12-03   389.264791   91.398966
2106-12-10   386.549452   90.952206
2106-12-17   383.853055   90.507630
2106-12-24   381.175466   90.065228
2106-12-31   378.516555   89.624988

[366 rows x 2 columns]

## columns by their _left_ or _right_ part of their names
semicolon **:** acts as name separator
- _left_**:**_right_

In [14]:
sample_prod['WOPR']

               WOPR:P2      WOPR:P1
               sm3/day      stb/day
DATE
2100-01-01  536.000000  4872.000000
2100-01-08  533.380024  4838.015086
2100-01-15  530.772855  4804.267236
2100-01-22  528.178429  4770.754795
2100-01-29  525.596686  4737.476123
...                ...          ...
2106-12-03   91.398966   389.264791
2106-12-10   90.952206   386.549452
2106-12-17   90.507630   383.853055
2106-12-24   90.065228   381.175466
2106-12-31   89.624988   378.516555

[366 rows x 2 columns]

In [15]:
sample_prod['P1']

                WOPR:P1      WWPR:P1      WBHP:P1
                stb/day      stb/day         psia
DATE
2100-01-01  4872.000000     0.000000  5012.100000
2100-01-08  4838.015086    12.707564  4987.600782
2100-01-15  4804.267236    25.304309  4963.221317
2100-01-22  4770.754795    37.791219  4938.961019
2100-01-29  4737.476123    50.169277  4914.819305
...                 ...          ...          ...
2106-12-03   389.264791  6782.302094   854.665589
2106-12-10   386.549452  7096.137397   850.487971
2106-12-17   383.853055  7443.580545   846.330773
2106-12-24   381.175466  7830.322069   842.193896
2106-12-31   378.516555  8263.413916   838.077240

[366 rows x 3 columns]

## slice of column names

In [16]:
sample_prod['WWPR:P1':'WOPR:P2']

                WWPR:P1      WBHP:P1     WOPR:P2
                stb/day         psia     sm3/day
DATE
2100-01-01     0.000000  5012.100000  536.000000
2100-01-08    12.707564  4987.600782  533.380024
2100-01-15    25.304309  4963.221317  530.772855
2100-01-22    37.791219  4938.961019  528.178429
2100-01-29    50.169277  4914.819305  525.596686
...                 ...          ...         ...
2106-12-03  6782.302094   854.665589   91.398966
2106-12-10  7096.137397   850.487971   90.952206
2106-12-17  7443.580545   846.330773   90.507630
2106-12-24  7830.322069   842.193896   90.065228
2106-12-31  8263.413916   838.077240   89.624988

[366 rows x 3 columns]

## name patterns
following **fnmatch** patterns

In [17]:
sample_prod['W?PR*2']

               WOPR:P2     WWPR:P2
               sm3/day     sm3/day
DATE
2100-01-01  536.000000    0.000000
2100-01-08  533.380024    2.619792
2100-01-15  530.772855    5.226413
2100-01-22  528.178429    7.819928
2100-01-29  525.596686   10.400402
...                ...         ...
2106-12-03   91.398966  433.506733
2106-12-10   90.952206  433.911970
2106-12-17   90.507630  434.315018
2106-12-24   90.065228  434.715890
2106-12-31   89.624988  435.114595

[366 rows x 2 columns]

In [18]:
sample_prod['W?PR*']

                WOPR:P1      WWPR:P1     WOPR:P2     WWPR:P2
                stb/day      stb/day     sm3/day     sm3/day
DATE
2100-01-01  4872.000000     0.000000  536.000000    0.000000
2100-01-08  4838.015086    12.707564  533.380024    2.619792
2100-01-15  4804.267236    25.304309  530.772855    5.226413
2100-01-22  4770.754795    37.791219  528.178429    7.819928
2100-01-29  4737.476123    50.169277  525.596686   10.400402
...                 ...          ...         ...         ...
2106-12-03   389.264791  6782.302094   91.398966  433.506733
2106-12-10   386.549452  7096.137397   90.952206  433.911970
2106-12-17   383.853055  7443.580545   90.507630  434.315018
2106-12-24   381.175466  7830.322069   90.065228  434.715890
2106-12-31   378.516555  8263.413916   89.624988  435.114595

[366 rows x 4 columns]

## [ ] looks into the index, if not found in columns
and takes advantage of DateTimeIndex capabilities!

In [19]:
sample_prod['2100-04-09']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-04-09,4417.193459,168.173679,4679.798198,500.463246,35.501945,244.350552

In [20]:
sample_prod['2100-04']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-04-02,4448.222288,156.831739,4702.785482,502.921534,33.048379,244.401871
2100-04-09,4417.193459,168.173679,4679.798198,500.463246,35.501945,244.350552
2100-04-16,4386.381074,179.417105,4656.923276,498.016974,37.943165,244.299244
2100-04-23,4355.783623,190.562918,4634.160167,495.582660,40.372098,244.247947
2100-04-30,4325.399605,201.612013,4611.508325,493.160245,42.788806,244.196660

In [21]:
sample_prod['2100']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228
2100-02-05,4704.429588,62.439454,4890.795597,523.027561,12.967899,244.812812
2100-02-12,4671.613571,74.602718,4866.889316,520.470995,15.522484,244.761406
2100-02-19,4639.026464,86.660027,4843.099890,517.926925,18.064221,244.710012
2100-02-26,4606.666670,98.612335,4819.426748,515.395291,20.593174,244.658628
2100-03-05,4574.532604,110.460587,4795.869319,512.876031,23.109405,244.607255
2100-03-12,4542.622691,122.205724,4772.427040,510.369086,25.612979,244.555893
2100-03-19,4510.935367,133.848678,4749.099347,507.874394,28.103958,244.504542
2100-03-26,4479.469080,145.390376,4725.885680,505.391897,30.582403,244.453201
2100-04-02,4448.222288,156.831739,4702.785482,502.921534,33.048379,244.401871
2100-04-09,4417.193459,168.173679,4679.798198,500.463246,35.501945,244.350552
2100-04-16,4386.381074,179.417105,4656.923276,498.016974,37.943165,244.299244
2100-04-23,4355.783623,190.562918,4634.160167,495.582660,40.372098,244.247947
2100-04-30,4325.399605,201.612013,4611.508325,493.160245,42.788806,244.196660
2100-05-07,4295.227534,212.565279,4588.967205,490.749670,45.193350,244.145384
2100-05-14,4265.265929,223.423599,4566.536266,488.350879,47.585790,244.094119
2100-05-21,4235.513323,234.187850,4544.214971,485.963812,49.966186,244.042864
2100-05-28,4205.968258,244.858903,4522.002781,483.588414,52.334597,243.991621
2100-06-04,4176.629286,255.437623,4499.899166,481.224627,54.691084,243.940388
2100-06-11,4147.494970,265.924869,4477.903593,478.872394,57.035705,243.889166
2100-06-18,4118.563883,276.321495,4456.015535,476.531659,59.368518,243.837955
2100-06-25,4089.834605,286.628348,4434.234466,474.202365,61.689584,243.786754
2100-07-02,4061.305731,296.846270,4412.559863,471.884457,63.998959,243.735564
2100-07-09,4032.975861,306.976098,4390.991206,469.577879,66.296702,243.684385
2100-07-16,4004.843607,317.018662,4369.527977,467.282575,68.582870,243.633217
2100-07-23,3976.907592,326.974788,4348.169661,464.998491,70.857522,243.582059
2100-07-30,3949.166446,336.845295,4326.915744,462.725572,73.120713,243.530912
2100-08-06,3921.618810,346.630999,4305.765717,460.463763,75.372502,243.479776
2100-08-13,3894.263335,356.332707,4284.719071,458.213009,77.612943,243.428651
2100-08-20,3867.098679,365.951223,4263.775302,455.973257,79.842094,243.377536
2100-08-27,3840.123511,375.487346,4242.933906,453.744453,82.060011,243.326432
2100-09-03,3813.336510,384.941870,4222.194383,451.526544,84.266750,243.275339
2100-09-10,3786.736364,394.315582,4201.556236,449.319475,86.462365,243.224257
2100-09-17,3760.321768,403.609265,4181.018967,447.123195,88.646912,243.173185
2100-09-24,3734.091429,412.823697,4160.582086,444.937650,90.820446,243.122124
2100-10-01,3708.044061,421.959650,4140.245100,442.762789,92.983021,243.071073
2100-10-08,3682.178388,431.017894,4120.007521,440.598558,95.134692,243.020034
2100-10-15,3656.493143,439.999191,4099.868865,438.444906,97.275513,242.969005
2100-10-22,3630.987066,448.904299,4079.828646,436.301781,99.405537,242.917987
2100-10-29,3605.658909,457.733972,4059.886384,434.169131,101.524819,242.866980
2100-11-05,3580.507429,466.488958,4040.041600,432.046906,103.633411,242.815983
2100-11-12,3555.531395,475.170001,4020.293818,429.935054,105.731367,242.764997
2100-11-19,3530.729583,483.777841,4000.642563,427.833526,107.818738,242.714021
2100-11-26,3506.100778,492.313212,3981.087364,425.742269,109.895579,242.663057
2100-12-03,3481.643772,500.776845,3961.627751,423.661235,111.961940,242.612103
2100-12-10,3457.357367,509.169465,3942.263256,421.590372,114.017875,242.561160
2100-12-17,3433.240373,517.491794,3922.993416,419.529632,116.063434,242.510227
2100-12-24,3409.291609,525.744549,3903.817767,417.478966,118.098669,242.459306
2100-12-31,3385.509901,533.928441,3884.735849,415.438322,120.123631,242.408394

In [22]:
sample_prod['2100-04-09':'2100-05-15']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-04-09,4417.193459,168.173679,4679.798198,500.463246,35.501945,244.350552
2100-04-16,4386.381074,179.417105,4656.923276,498.016974,37.943165,244.299244
2100-04-23,4355.783623,190.562918,4634.160167,495.582660,40.372098,244.247947
2100-04-30,4325.399605,201.612013,4611.508325,493.160245,42.788806,244.196660
2100-05-07,4295.227534,212.565279,4588.967205,490.749670,45.193350,244.145384
2100-05-14,4265.265929,223.423599,4566.536266,488.350879,47.585790,244.094119

## get from `SimSeries` instances

In [23]:
single_column['2100-01-08']

4838.015085970722_stb/day

In [24]:
single_column['2100-05']

DATE
2100-05-07    4295.227534
2100-05-14    4265.265929
2100-05-21    4235.513323
2100-05-28    4205.968258
Name: WOPR:P1, dtype: float64, units: stb/day

In [25]:
single_column['2100-04-30': '2100-06-12']

DATE
2100-04-30    4325.399605
2100-05-07    4295.227534
2100-05-14    4265.265929
2100-05-21    4235.513323
2100-05-28    4205.968258
2100-06-04    4176.629286
2100-06-11    4147.494970
Name: WOPR:P1, dtype: float64, units: stb/day

In [26]:
single_column[['2100-01-08', '2100-02-19', '2100-05-07']]

DATE
2100-01-08    4838.015086
2100-02-19    4639.026464
2100-05-07    4295.227534
Name: WOPR:P1, dtype: float64, units: stb/day

## [_index_, _column_] 
Will behave as `.loc[_index_, _column_]` but **`.loc`** will be faster:

In [27]:
sample_prod['2100-02-26', 'P1']

               WOPR:P1    WWPR:P1      WBHP:P1
               stb/day    stb/day         psia
DATE
2100-02-26  4606.66667  98.612335  4819.426748

In [28]:
sample_prod['2100-04', 'P1']

                WOPR:P1     WWPR:P1      WBHP:P1
                stb/day     stb/day         psia
DATE
2100-04-02  4448.222288  156.831739  4702.785482
2100-04-09  4417.193459  168.173679  4679.798198
2100-04-16  4386.381074  179.417105  4656.923276
2100-04-23  4355.783623  190.562918  4634.160167
2100-04-30  4325.399605  201.612013  4611.508325

In [29]:
sample_prod['2100-04':'2100-06', 'P1']

                WOPR:P1     WWPR:P1      WBHP:P1
                stb/day     stb/day         psia
DATE
2100-04-02  4448.222288  156.831739  4702.785482
2100-04-09  4417.193459  168.173679  4679.798198
2100-04-16  4386.381074  179.417105  4656.923276
2100-04-23  4355.783623  190.562918  4634.160167
2100-04-30  4325.399605  201.612013  4611.508325
2100-05-07  4295.227534  212.565279  4588.967205
2100-05-14  4265.265929  223.423599  4566.536266
2100-05-21  4235.513323  234.187850  4544.214971
2100-05-28  4205.968258  244.858903  4522.002781
2100-06-04  4176.629286  255.437623  4499.899166
2100-06-11  4147.494970  265.924869  4477.903593
2100-06-18  4118.563883  276.321495  4456.015535
2100-06-25  4089.834605  286.628348  4434.234466

In [30]:
sample_prod['2100-02-26', 'WBHP:P1']

4819.426747568031_psia

# Indexers
## .loc

In [31]:
sample_prod.loc['2100-02-26']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-02-26,4606.66667,98.612335,4819.426748,515.395291,20.593174,244.658628

In [32]:
sample_prod.loc['2100-01']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228

In [33]:
sample_prod.loc['2100']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228
2100-02-05,4704.429588,62.439454,4890.795597,523.027561,12.967899,244.812812
2100-02-12,4671.613571,74.602718,4866.889316,520.470995,15.522484,244.761406
2100-02-19,4639.026464,86.660027,4843.099890,517.926925,18.064221,244.710012
2100-02-26,4606.666670,98.612335,4819.426748,515.395291,20.593174,244.658628
2100-03-05,4574.532604,110.460587,4795.869319,512.876031,23.109405,244.607255
2100-03-12,4542.622691,122.205724,4772.427040,510.369086,25.612979,244.555893
2100-03-19,4510.935367,133.848678,4749.099347,507.874394,28.103958,244.504542
2100-03-26,4479.469080,145.390376,4725.885680,505.391897,30.582403,244.453201
2100-04-02,4448.222288,156.831739,4702.785482,502.921534,33.048379,244.401871
2100-04-09,4417.193459,168.173679,4679.798198,500.463246,35.501945,244.350552
2100-04-16,4386.381074,179.417105,4656.923276,498.016974,37.943165,244.299244
2100-04-23,4355.783623,190.562918,4634.160167,495.582660,40.372098,244.247947
2100-04-30,4325.399605,201.612013,4611.508325,493.160245,42.788806,244.196660
2100-05-07,4295.227534,212.565279,4588.967205,490.749670,45.193350,244.145384
2100-05-14,4265.265929,223.423599,4566.536266,488.350879,47.585790,244.094119
2100-05-21,4235.513323,234.187850,4544.214971,485.963812,49.966186,244.042864
2100-05-28,4205.968258,244.858903,4522.002781,483.588414,52.334597,243.991621
2100-06-04,4176.629286,255.437623,4499.899166,481.224627,54.691084,243.940388
2100-06-11,4147.494970,265.924869,4477.903593,478.872394,57.035705,243.889166
2100-06-18,4118.563883,276.321495,4456.015535,476.531659,59.368518,243.837955
2100-06-25,4089.834605,286.628348,4434.234466,474.202365,61.689584,243.786754
2100-07-02,4061.305731,296.846270,4412.559863,471.884457,63.998959,243.735564
2100-07-09,4032.975861,306.976098,4390.991206,469.577879,66.296702,243.684385
2100-07-16,4004.843607,317.018662,4369.527977,467.282575,68.582870,243.633217
2100-07-23,3976.907592,326.974788,4348.169661,464.998491,70.857522,243.582059
2100-07-30,3949.166446,336.845295,4326.915744,462.725572,73.120713,243.530912
2100-08-06,3921.618810,346.630999,4305.765717,460.463763,75.372502,243.479776
2100-08-13,3894.263335,356.332707,4284.719071,458.213009,77.612943,243.428651
2100-08-20,3867.098679,365.951223,4263.775302,455.973257,79.842094,243.377536
2100-08-27,3840.123511,375.487346,4242.933906,453.744453,82.060011,243.326432
2100-09-03,3813.336510,384.941870,4222.194383,451.526544,84.266750,243.275339
2100-09-10,3786.736364,394.315582,4201.556236,449.319475,86.462365,243.224257
2100-09-17,3760.321768,403.609265,4181.018967,447.123195,88.646912,243.173185
2100-09-24,3734.091429,412.823697,4160.582086,444.937650,90.820446,243.122124
2100-10-01,3708.044061,421.959650,4140.245100,442.762789,92.983021,243.071073
2100-10-08,3682.178388,431.017894,4120.007521,440.598558,95.134692,243.020034
2100-10-15,3656.493143,439.999191,4099.868865,438.444906,97.275513,242.969005
2100-10-22,3630.987066,448.904299,4079.828646,436.301781,99.405537,242.917987
2100-10-29,3605.658909,457.733972,4059.886384,434.169131,101.524819,242.866980
2100-11-05,3580.507429,466.488958,4040.041600,432.046906,103.633411,242.815983
2100-11-12,3555.531395,475.170001,4020.293818,429.935054,105.731367,242.764997
2100-11-19,3530.729583,483.777841,4000.642563,427.833526,107.818738,242.714021
2100-11-26,3506.100778,492.313212,3981.087364,425.742269,109.895579,242.663057
2100-12-03,3481.643772,500.776845,3961.627751,423.661235,111.961940,242.612103
2100-12-10,3457.357367,509.169465,3942.263256,421.590372,114.017875,242.561160
2100-12-17,3433.240373,517.491794,3922.993416,419.529632,116.063434,242.510227
2100-12-24,3409.291609,525.744549,3903.817767,417.478966,118.098669,242.459306
2100-12-31,3385.509901,533.928441,3884.735849,415.438322,120.123631,242.408394

In [34]:
sample_prod.loc['2100-12-24':'2101-02']

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-12-24,3409.291609,525.744549,3903.817767,417.478966,118.098669,242.459306
2100-12-31,3385.509901,533.928441,3884.735849,415.438322,120.123631,242.408394
2101-01-07,3361.894083,542.044180,3865.747203,413.407654,122.138371,242.357494
2101-01-14,3338.442999,550.092469,3846.851375,411.386911,124.142941,242.306604
2101-01-21,3315.155500,558.074008,3828.047909,409.376046,126.137389,242.255725
2101-01-28,3292.030443,565.989494,3809.336355,407.375010,128.121767,242.204857
2101-02-04,3269.066697,573.839616,3790.716263,405.383755,130.096125,242.153999
2101-02-11,3246.263136,581.625064,3772.187187,403.402233,132.060511,242.103152
2101-02-18,3223.618642,589.346521,3753.748681,401.430397,134.014977,242.052316
2101-02-25,3201.132106,597.004665,3735.400303,399.468199,135.959570,242.001490

In [35]:
sample_prod.loc[:,'P1']

                WOPR:P1      WWPR:P1      WBHP:P1
                stb/day      stb/day         psia
DATE
2100-01-01  4872.000000     0.000000  5012.100000
2100-01-08  4838.015086    12.707564  4987.600782
2100-01-15  4804.267236    25.304309  4963.221317
2100-01-22  4770.754795    37.791219  4938.961019
2100-01-29  4737.476123    50.169277  4914.819305
...                 ...          ...          ...
2106-12-03   389.264791  6782.302094   854.665589
2106-12-10   386.549452  7096.137397   850.487971
2106-12-17   383.853055  7443.580545   846.330773
2106-12-24   381.175466  7830.322069   842.193896
2106-12-31   378.516555  8263.413916   838.077240

[366 rows x 3 columns]

In [36]:
sample_prod.loc['2100-12-24':'2101-01-15', 'P1']

                WOPR:P1     WWPR:P1      WBHP:P1
                stb/day     stb/day         psia
DATE
2100-12-24  3409.291609  525.744549  3903.817767
2100-12-31  3385.509901  533.928441  3884.735849
2101-01-07  3361.894083  542.044180  3865.747203
2101-01-14  3338.442999  550.092469  3846.851375

In [37]:
sample_prod.loc['2100-12-24':'2101-01-15', 'WBHP:P1': 'WWPR:P2']

                WBHP:P1     WOPR:P2     WWPR:P2
                   psia     sm3/day     sm3/day
DATE
2100-12-24  3903.817767  417.478966  118.098669
2100-12-31  3884.735849  415.438322  120.123631
2101-01-07  3865.747203  413.407654  122.138371
2101-01-14  3846.851375  411.386911  124.142941

In [38]:
sample_prod.loc['2100-12-24', 'P1']

                WOPR:P1     WWPR:P1      WBHP:P1
                stb/day     stb/day         psia
DATE
2100-12-24  3409.291609  525.744549  3903.817767

In [39]:
sample_prod.loc['2100-12-24', 'WOPR:P1']

3409.291608963025_stb/day

In [40]:
sample_prod.loc['2100-02-26', 'WBHP:P1']

4819.426747568031_psia

## iloc

In [41]:
sample_prod.iloc[0]

           WOPR:P1 WWPR:P1 WBHP:P1 WOPR:P2 WWPR:P2 WBHP:P2
           stb/day stb/day    psia sm3/day sm3/day   barsa
DATE
2100-01-01  4872.0     0.0  5012.1   536.0     0.0  245.07

In [42]:
sample_prod.iloc[0:5]

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228

In [43]:
sample_prod.iloc[0:5, 0:3]

                WOPR:P1    WWPR:P1      WBHP:P1
                stb/day    stb/day         psia
DATE
2100-01-01  4872.000000   0.000000  5012.100000
2100-01-08  4838.015086  12.707564  4987.600782
2100-01-15  4804.267236  25.304309  4963.221317
2100-01-22  4770.754795  37.791219  4938.961019
2100-01-29  4737.476123  50.169277  4914.819305

In [44]:
sample_prod.iloc[0:5, 0]

DATE
2100-01-01    4872.000000
2100-01-08    4838.015086
2100-01-15    4804.267236
2100-01-22    4770.754795
2100-01-29    4737.476123
Name: WOPR:P1, dtype: float64

In [45]:
sample_prod.iloc[:, 0]

DATE
2100-01-01    4872.000000
2100-01-08    4838.015086
2100-01-15    4804.267236
2100-01-22    4770.754795
2100-01-29    4737.476123
                 ...
2106-12-03     389.264791
2106-12-10     386.549452
2106-12-17     383.853055
2106-12-24     381.175466
2106-12-31     378.516555
Name: WOPR:P1, Length: 366, dtype: float64

In [46]:
sample_prod.iloc[:, 0:3]

                WOPR:P1      WWPR:P1      WBHP:P1
                stb/day      stb/day         psia
DATE
2100-01-01  4872.000000     0.000000  5012.100000
2100-01-08  4838.015086    12.707564  4987.600782
2100-01-15  4804.267236    25.304309  4963.221317
2100-01-22  4770.754795    37.791219  4938.961019
2100-01-29  4737.476123    50.169277  4914.819305
...                 ...          ...          ...
2106-12-03   389.264791  6782.302094   854.665589
2106-12-10   386.549452  7096.137397   850.487971
2106-12-17   383.853055  7443.580545   846.330773
2106-12-24   381.175466  7830.322069   842.193896
2106-12-31   378.516555  8263.413916   838.077240

[366 rows x 3 columns]

In [47]:
sample_prod.iloc[1:7,[0, 4]]

                WOPR:P1    WWPR:P2
                stb/day    sm3/day
DATE
2100-01-08  4838.015086   2.619792
2100-01-15  4804.267236   5.226413
2100-01-22  4770.754795   7.819928
2100-01-29  4737.476123  10.400402
2100-02-05  4704.429588  12.967899
2100-02-12  4671.613571  15.522484

# arithethic operations

In [48]:
sample_prod['WOPR']

               WOPR:P2      WOPR:P1
               sm3/day      stb/day
DATE
2100-01-01  536.000000  4872.000000
2100-01-08  533.380024  4838.015086
2100-01-15  530.772855  4804.267236
2100-01-22  528.178429  4770.754795
2100-01-29  525.596686  4737.476123
...                ...          ...
2106-12-03   91.398966   389.264791
2106-12-10   90.952206   386.549452
2106-12-17   90.507630   383.853055
2106-12-24   90.065228   381.175466
2106-12-31   89.624988   378.516555

[366 rows x 2 columns]

In [49]:
sample_prod['WOPR'].sum(axis=1)

             WOPR:P.sum
                sm3/day
DATE
2100-01-01  1310.585703
2100-01-08  1302.562561
2100-01-15  1294.589915
2100-01-22  1286.667440
2100-01-29  1278.794812
...                 ...
2106-12-03   153.287090
2106-12-10   152.408626
2106-12-17   151.535358
2106-12-24   150.667253
2106-12-31   149.804280

[366 rows x 1 columns]

In [50]:
sample_prod['WOPR'].sum(axis=0).T

          WOPR:P2        WOPR:P1
          sm3/day        stb/day
DATE
.sum  91409.93606  644554.085955

In [51]:
sample_prod['WOPR:P1'] + sample_prod['WOPR:P2']

DATE
2100-01-01    8243.340304
2100-01-08    8192.876229
2100-01-15    8142.729769
2100-01-22    8092.898875
2100-01-29    8043.381514
                 ...
2106-12-03     964.147285
2106-12-10     958.621912
2106-12-17     953.129216
2106-12-24     947.668997
2106-12-31     942.241057
Name: WOPR:P1+P2, Length: 366, dtype: float64, units: stb/day

In [52]:
sample_prod[['WOPR:P2']] + sample_prod[['WOPR:P1']]

             WOPR:P2∩P1
                sm3/day
DATE
2100-01-01  1310.585703
2100-01-08  1302.562561
2100-01-15  1294.589915
2100-01-22  1286.667440
2100-01-29  1278.794812
...                 ...
2106-12-03   153.287090
2106-12-10   152.408626
2106-12-17   151.535358
2106-12-24   150.667253
2106-12-31   149.804280

[366 rows x 1 columns]