In [1]:
import simpandas as spd
#from simpandas import SimDataFrame, SimSeries

In [2]:
spd.__version__

'0.90.0'

In [3]:
sample_prod = spd.read_excel('./test/_testing_data/sample_prod.xlsx')
sample_prod

,DATE,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,date,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
0,2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
1,2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2,2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
3,2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
4,2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228
...,...,...,...,...,...,...,...
361,2106-12-03,389.264791,6782.302094,854.665589,91.398966,433.506733,227.178007
362,2106-12-10,386.549452,7096.137397,850.487971,90.952206,433.911970,227.130305
363,2106-12-17,383.853055,7443.580545,846.330773,90.507630,434.315018,227.082613
364,2106-12-24,381.175466,7830.322069,842.193896,90.065228,434.715890,227.034930
365,2106-12-31,378.516555,8263.413916,838.077240,89.624988,435.114595,226.987258

In [4]:
sample_prod.to_summary('d:/git/TEST_SAMPLE_PROD.SMSPEC')

In [5]:
vdb = spd.read_vdb(r'D:\git\datafiletoolbox_samples\SPE3\vip\spe.vdb')

In [6]:
vdb

,QGP:WELL_1,QGP:WELL_2,QGP:WELL_3,QOP:WELL_1,QOP:WELL_2,QOP:WELL_3,QWP:WELL_1,QWP:WELL_2,QWP:WELL_3,QGI:WELL_1,...,CWIR:WELL_3,IGC:WELL_1,IGC:WELL_2,IGC:WELL_3,IFS:WELL_1,IFS:WELL_2,IFS:WELL_3,IAR:WELL_1,IAR:WELL_2,IAR:WELL_3
,MSCF / DAY,MSCF / DAY,MSCF / DAY,STB / DAY,STB / DAY,STB / DAY,STB / DAY,STB / DAY,STB / DAY,MSCF / DAY,...,MRB,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
TIME,,,,,,,,,,,,,,,,,,,,,
365.0,0.0,0.0,6200.0,0.0,0.000000,902.706848,0.0,0.000000,9.948227,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
730.0,0.0,6200.0,0.0,0.0,820.621826,0.000000,0.0,11.536452,0.000000,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1095.0,0.0,0.0,6200.0,0.0,0.000000,745.961426,0.0,0.000000,12.730264,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1460.0,0.0,6200.0,0.0,0.0,656.070068,0.000000,0.0,12.680438,0.000000,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1825.0,0.0,0.0,6200.0,0.0,0.000000,549.916016,0.0,0.000000,11.476529,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2180.0,0.0,6200.0,0.0,0.0,479.944122,0.000000,0.0,10.612055,0.000000,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2555.0,0.0,0.0,6200.0,0.0,0.000000,424.339935,0.0,0.000000,9.561948,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2920.0,0.0,6200.0,0.0,0.0,366.309387,0.000000,0.0,8.488557,0.000000,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3285.0,0.0,0.0,6200.0,0.0,0.000000,319.666870,0.0,0.000000,7.781012,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3650.0,0.0,6200.0,0.0,0.0,270.550140,0.000000,0.0,7.102402,0.000000,4700.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4380.0,0.0,0.0,6200.0,0.0,0.000000,177.650101,0.0,0.000000,7.461922,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4745.0,0.0,6200.0,0.0,0.0,149.847092,0.000000,0.0,8.469715,0.000000,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5110.0,0.0,0.0,6200.0,0.0,0.000000,132.455215,0.0,0.000000,10.142606,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5475.0,0.0,6200.0,0.0,0.0,126.997665,0.000000,0.0,13.139357,0.000000,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [7]:
vdb.wells

['WELL_2', 'WELL_3', 'WELL_1']

In [8]:
rkf = spd.read_vdb(r'D:\git\datafiletoolbox_samples\VIP\RKF.vdb')

In [12]:
rkf

,QGP:1.0.0,QGP:RKF-01P,QGP:RKF-02P,QGP:RKF-02I,QGP:RKF-03I,QGP:RKF-04P,QGP:RKF-05P,QGP:RKF-06I,QGP:RKF-07P,QGP:RKF-08P,...,IAR:RKF-09P,IAR:RKF-10I,IAR:RKF-11I,IAR:RKF-12P,IAR:RKF-13P,IAR:RKF-14P,IAR:RKF-15P,IAR:RKF-16P,IAR:RKF-17P,IAR:RKF-18P
,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,KSM3 / DAY,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
TIME,,,,,,,,,,,,,,,,,,,,,
0.200000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN
0.400000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN
0.612724,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN
0.927862,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN
1.305887,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7589.000000,0.0,0.0,0.000000,0.0,0.0,313.884125,0.0,0.000000,85.946777,161.446182,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
7589.688477,0.0,0.0,319.081909,0.0,0.0,0.000000,0.0,250.202850,5.798393,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
7590.000000,0.0,0.0,316.952484,0.0,0.0,0.000000,0.0,250.203003,5.799576,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
7590.594727,0.0,0.0,0.000000,0.0,0.0,311.856018,0.0,0.000000,85.593781,172.418259,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
7591.000000,0.0,0.0,0.000000,0.0,0.0,311.797546,0.0,0.000000,85.604301,172.257980,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0

In [13]:
rkf.columns

Index(['QGP:1.0.0', 'QGP:RKF-01P', 'QGP:RKF-02P', 'QGP:RKF-02I', 'QGP:RKF-03I',
       'QGP:RKF-04P', 'QGP:RKF-05P', 'QGP:RKF-06I', 'QGP:RKF-07P',
       'QGP:RKF-08P',
       ...
       'IAR:RKF-09P', 'IAR:RKF-10I', 'IAR:RKF-11I', 'IAR:RKF-12P',
       'IAR:RKF-13P', 'IAR:RKF-14P', 'IAR:RKF-15P', 'IAR:RKF-16P',
       'IAR:RKF-17P', 'IAR:RKF-18P'],
      dtype='object', length=1060)

In [14]:
rkf.wells

['RKF-15P',
 'RKF-03I',
 'RKF-08P',
 'RKF-16P',
 'RKF-14P',
 'RKF-02I',
 'RKF-01P',
 'RKF-11I',
 'RKF-02P',
 'RKF-12P',
 'RKF-18P',
 'RKF-10I',
 'RKF-06I',
 '1.0.0',
 'RKF-13P',
 'RKF-05P',
 'RKF-04P',
 'RKF-07P',
 'RKF-17P',
 'RKF-09P']

In [4]:
sample_ecl = spd.read_summary(r'D:\git\datafiletoolbox_samples\ECL\ECL.SMSPEC')

In [ ]:
sample_ecl

In [ ]:
sample_ix = spd.read_summary('d:/git/datafiletoolbox_samples/IX/IX.SMSPEC')

In [ ]:
sample_ix

In [ ]:
[(i, c) for i, c in enumerate(sample_ecl.columns) if c=='GOPGR:BSAND']

In [4]:
sample_sumry = spd.read_summary(r'D:\git\datafiletoolbox_samples\SPE3\e300\SPE3_GASCOND.SMSPEC')

In [5]:
len(sample_sumry.columns)

83

In [6]:
[c for c in sample_sumry.columns if c.startswith('B')]

['BVOIL:7,7,4',
 'BSOIL:7,7,4',
 'BSWAT:7,7,4',
 'BSGAS:7,7,4',
 'BPRES:1,1,1',
 'BXMF_6:1,1,1',
 'BYMF_6:1,1,1',
 'BSSOLID:7,7,1',
 'BPRES:7,7,1']

In [7]:
len(sample_sumry.units)

83

In [8]:
list(sample_sumry.columns)

['TIME',
 'YEARS',
 'FOPR',
 'WOPR:I',
 'WOPR:P',
 'FOPT',
 'WOPT:I',
 'WOPT:P',
 'FWPR',
 'WWPR:I',
 'WWPR:P',
 'FWPT',
 'WWPT:I',
 'WWPT:P',
 'FWIR',
 'WWIR:I',
 'WWIR:P',
 'FWIT',
 'WWIT:I',
 'WWIT:P',
 'FGPR',
 'WGPR:I',
 'WGPR:P',
 'FGPT',
 'WGPT:I',
 'WGPT:P',
 'FGIR',
 'WGIR:I',
 'WGIR:P',
 'FGIT',
 'WGIT:I',
 'WGIT:P',
 'FVPR',
 'WVPR:I',
 'WVPR:P',
 'FVPT',
 'WVPT:I',
 'WVPT:P',
 'FVIR',
 'WVIR:I',
 'WVIR:P',
 'FVIT',
 'WVIT:I',
 'WVIT:P',
 'FWCT',
 'WWCT:I',
 'WWCT:P',
 'FGOR',
 'WGOR:I',
 'WGOR:P',
 'FWGR',
 'WWGR:I',
 'WWGR:P',
 'WBHP:I',
 'WBHP:P',
 'WTHP:I',
 'WTHP:P',
 'FPR',
 'WPI:I',
 'WPI:P',
 'FOIP',
 'FOIPL',
 'FOIPG',
 'FWIP',
 'FGIP',
 'FGIPL',
 'FGIPG',
 'FPRH',
 'WXMF_1:P',
 'WXMF_2:P',
 'WXMF_3:P',
 'WXMF_4:P',
 'BVOIL:7,7,4',
 'BSOIL:7,7,4',
 'BSWAT:7,7,4',
 'BSGAS:7,7,4',
 'BPRES:1,1,1',
 'BXMF_6:1,1,1',
 'BYMF_6:1,1,1',
 'BSSOLID:7,7,1',
 'BPRES:7,7,1',
 'MSUMLINS',
 'MSUMNEWT']

In [9]:
sample_sumry.index

DatetimeIndex(['1990-01-02', '1990-01-04', '1990-01-08', '1990-01-16',
               '1990-02-01', '1990-03-05', '1990-04-24', '1990-06-13',
               '1990-08-02', '1990-09-21',
               ...
               '2003-11-18', '2003-12-29', '2004-02-17', '2004-04-07',
               '2004-05-18', '2004-06-28', '2004-08-17', '2004-10-06',
               '2004-11-17', '2004-12-28'],
              dtype='datetime64[ns]', name='DATE', length=125, freq=None)

In [10]:
sample_sumry

,TIME,YEARS,FOPR,WOPR:I,WOPR:P,FOPT,WOPT:I,WOPT:P,FWPR,WWPR:I,...,"BSOIL:7,7,4","BSWAT:7,7,4","BSGAS:7,7,4","BPRES:1,1,1","BXMF_6:1,1,1","BYMF_6:1,1,1","BSSOLID:7,7,1","BPRES:7,7,1",MSUMLINS,MSUMNEWT
,DAYS,YEARS,STB/DAY,STB/DAY,STB/DAY,STB,STB,STB,STB/DAY,STB/DAY,...,NaN,NaN,NaN,PSIA,NaN,NaN,NaN,PSIA,NaN,NaN
DATE,,,,,,,,,,,,,,,,,,,,,
1990-01-02,1.00,0.002738,959.345154,0.0,959.345154,9.593452e+02,0.0,9.593452e+02,14.707206,0.0,...,0.000000,0.290862,0.709138,3536.609131,0.095036,0.095036,0.000000,3517.210693,7.0,2.0
1990-01-04,3.00,0.008214,959.034973,0.0,959.034973,2.877415e+03,0.0,2.877415e+03,14.700819,0.0,...,0.000000,0.290790,0.709210,3539.591309,0.130705,0.091959,0.000000,3514.066162,15.0,4.0
1990-01-08,7.00,0.019165,957.859497,0.0,957.859497,6.708853e+03,0.0,6.708853e+03,14.679468,0.0,...,0.000000,0.290645,0.709355,3538.914307,0.131552,0.086519,0.000000,3511.135986,24.0,6.0
1990-01-16,15.00,0.041068,955.881836,0.0,955.881836,1.435591e+04,0.0,1.435591e+04,14.632105,0.0,...,0.000148,0.290358,0.709494,3535.144043,0.078153,0.078153,0.000000,3506.754150,36.0,8.0
1990-02-01,31.00,0.084873,950.368042,0.0,950.368042,2.956180e+04,0.0,2.956180e+04,14.594519,0.0,...,0.003851,0.289816,0.706333,3527.480469,0.067428,0.067428,0.000000,3498.808838,48.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2004-06-28,5292.50,14.490075,140.163162,0.0,140.163162,2.568540e+06,0.0,2.568540e+06,15.614312,0.0,...,0.185116,0.275908,0.538976,1223.195801,0.046342,0.046342,0.061911,1209.205444,1321.0,242.0
2004-08-17,5342.50,14.626967,138.685410,0.0,138.685410,2.575474e+06,0.0,2.575474e+06,15.964738,0.0,...,0.182453,0.275937,0.541609,1184.682983,0.046342,0.046342,0.061435,1170.397461,1332.0,244.0
2004-10-06,5392.50,14.763861,137.514679,0.0,137.514679,2.582350e+06,0.0,2.582350e+06,16.347706,0.0,...,0.179898,0.275936,0.544167,1146.004395,0.046342,0.046342,0.060952,1131.359741,1343.0,246.0
2004-11-17,5433.75,14.876797,136.687164,0.0,136.687164,2.587988e+06,0.0,2.587988e+06,16.690016,0.0,...,0.177635,0.275931,0.546434,1113.959595,0.046342,0.046342,0.060525,1098.929565,1354.0,248.0
2004-12-28,5475.00,14.989733,136.101837,0.0,136.101837,2.593602e+06,0.0,2.593602e+06,17.060028,0.0,...,0.175351,0.275920,0.548730,1081.771240,0.046342,0.046342,0.060094,1066.367065,1365.0,250.0

In [12]:
sample_prod.to_summary('D:/git/TEST_SAMPLE.SMSPEC')

TypeError: float() argument must be a string or a real number, not 'Timestamp'

In [10]:
sample_sumry.wells

['P', 'I']

In [11]:
type(sample_sumry)

SimDataFrame

In [12]:
[(i, c) for i, c in enumerate(sample_sumry.columns) if c=='FOPR']

[(2, 'FOPR')]

In [13]:
sample_sumry['FOPR'].df.diff(axis=1).sum()

FOPR    0.0
dtype: float64

In [14]:
sample_sumry.units

{'DATE': None,
 'YEARS': 'YEARS',
 'FOPR': 'STB/DAY',
 'WOPR:I': 'STB/DAY',
 'WOPR:P': 'STB/DAY',
 'FOPT': 'STB',
 'WOPT:I': 'STB',
 'WOPT:P': 'STB',
 'FWPR': 'STB/DAY',
 'WWPR:I': 'STB/DAY',
 'WWPR:P': 'STB/DAY',
 'FWPT': 'STB',
 'WWPT:I': 'STB',
 'WWPT:P': 'STB',
 'FWIR': 'STB/DAY',
 'WWIR:I': 'STB/DAY',
 'WWIR:P': 'STB/DAY',
 'FWIT': 'STB',
 'WWIT:I': 'STB',
 'WWIT:P': 'STB',
 'FGPR': 'MSCF/DAY',
 'WGPR:I': 'MSCF/DAY',
 'WGPR:P': 'MSCF/DAY',
 'FGPT': 'MSCF',
 'WGPT:I': 'MSCF',
 'WGPT:P': 'MSCF',
 'FGIR': 'MSCF/DAY',
 'WGIR:I': 'MSCF/DAY',
 'WGIR:P': 'MSCF/DAY',
 'FGIT': 'MSCF',
 'WGIT:I': 'MSCF',
 'WGIT:P': 'MSCF',
 'FVPR': 'RB/DAY',
 'WVPR:I': 'RB/DAY',
 'WVPR:P': 'RB/DAY',
 'FVPT': 'RB',
 'WVPT:I': 'RB',
 'WVPT:P': 'RB',
 'FVIR': 'RB/DAY',
 'WVIR:I': 'RB/DAY',
 'WVIR:P': 'RB/DAY',
 'FVIT': 'RB',
 'WVIT:I': 'RB',
 'WVIT:P': 'RB',
 'FWCT': None,
 'WWCT:I': None,
 'WWCT:P': None,
 'FGOR': 'MSCF/STB',
 'WGOR:I': 'MSCF/STB',
 'WGOR:P': 'MSCF/STB',
 'FWGR': 'STB/MSCF',
 'WWGR:I': 'STB/MSCF',
 'WWGR:P': 'STB/MSCF',
 'WBHP:I': 'PSIA',
 'WBHP:P': 'PSIA',
 'WTHP:I': 'PSIA',
 'WTHP:P': 'PSIA',
 'FPR': 'PSIA',
 'WPI:I': None,
 'WPI:P': None,
 'FOIP': 'STB',
 'FOIPL': 'STB',
 'FOIPG': 'STB',
 'FWIP': 'STB',
 'FGIP': 'MSCF',
 'FGIPL': 'MSCF',
 'FGIPG': 'MSCF',
 'FPRH': 'PSIA',
 'WXMF_1:P': None,
 'WXMF_2:P': None,
 'WXMF_3:P': None,
 'WXMF_4:P': None,
 'BVOIL:7,7,4': 'CP',
 'BSOIL:7,7,4': None,
 'BSWAT:7,7,4': None,
 'BSGAS:7,7,4': None,
 'BPRES:1,1,1': 'PSIA',
 'BXMF_6:1,1,1': None,
 'BYMF_6:1,1,1': None,
 'BSSOLID:7,7,1': None,
 'BPRES:7,7,1': 'PSIA',
 'MSUMLINS': None,
 'MSUMNEWT': None}

In [15]:
sample_sumry['FOPR'].units

'STB/DAY'

In [16]:
sample_sumry.get_units()

{'DATE': None,
 'YEARS': 'YEARS',
 'FOPR': 'STB/DAY',
 'WOPR:I': 'STB/DAY',
 'WOPR:P': 'STB/DAY',
 'FOPT': 'STB',
 'WOPT:I': 'STB',
 'WOPT:P': 'STB',
 'FWPR': 'STB/DAY',
 'WWPR:I': 'STB/DAY',
 'WWPR:P': 'STB/DAY',
 'FWPT': 'STB',
 'WWPT:I': 'STB',
 'WWPT:P': 'STB',
 'FWIR': 'STB/DAY',
 'WWIR:I': 'STB/DAY',
 'WWIR:P': 'STB/DAY',
 'FWIT': 'STB',
 'WWIT:I': 'STB',
 'WWIT:P': 'STB',
 'FGPR': 'MSCF/DAY',
 'WGPR:I': 'MSCF/DAY',
 'WGPR:P': 'MSCF/DAY',
 'FGPT': 'MSCF',
 'WGPT:I': 'MSCF',
 'WGPT:P': 'MSCF',
 'FGIR': 'MSCF/DAY',
 'WGIR:I': 'MSCF/DAY',
 'WGIR:P': 'MSCF/DAY',
 'FGIT': 'MSCF',
 'WGIT:I': 'MSCF',
 'WGIT:P': 'MSCF',
 'FVPR': 'RB/DAY',
 'WVPR:I': 'RB/DAY',
 'WVPR:P': 'RB/DAY',
 'FVPT': 'RB',
 'WVPT:I': 'RB',
 'WVPT:P': 'RB',
 'FVIR': 'RB/DAY',
 'WVIR:I': 'RB/DAY',
 'WVIR:P': 'RB/DAY',
 'FVIT': 'RB',
 'WVIT:I': 'RB',
 'WVIT:P': 'RB',
 'FWCT': None,
 'WWCT:I': None,
 'WWCT:P': None,
 'FGOR': 'MSCF/STB',
 'WGOR:I': 'MSCF/STB',
 'WGOR:P': 'MSCF/STB',
 'FWGR': 'STB/MSCF',
 'WWGR:I': 'STB/MSCF',
 'WWGR:P': 'STB/MSCF',
 'WBHP:I': 'PSIA',
 'WBHP:P': 'PSIA',
 'WTHP:I': 'PSIA',
 'WTHP:P': 'PSIA',
 'FPR': 'PSIA',
 'WPI:I': None,
 'WPI:P': None,
 'FOIP': 'STB',
 'FOIPL': 'STB',
 'FOIPG': 'STB',
 'FWIP': 'STB',
 'FGIP': 'MSCF',
 'FGIPL': 'MSCF',
 'FGIPG': 'MSCF',
 'FPRH': 'PSIA',
 'WXMF_1:P': None,
 'WXMF_2:P': None,
 'WXMF_3:P': None,
 'WXMF_4:P': None,
 'BVOIL:7,7,4': 'CP',
 'BSOIL:7,7,4': None,
 'BSWAT:7,7,4': None,
 'BSGAS:7,7,4': None,
 'BPRES:1,1,1': 'PSIA',
 'BXMF_6:1,1,1': None,
 'BYMF_6:1,1,1': None,
 'BSSOLID:7,7,1': None,
 'BPRES:7,7,1': 'PSIA',
 'MSUMLINS': None,
 'MSUMNEWT': None,
 'TIME': 'DAYS'}

In [6]:
sample_sumry['DATE']

0     1990-01-02
1     1990-01-04
2     1990-01-08
3     1990-01-16
4     1990-02-01
         ...
120   2004-06-28
121   2004-08-17
122   2004-10-06
123   2004-11-17
124   2004-12-28
Name: DATE, Length: 125, dtype: datetime64[ns], units: datetime

In [18]:
sample_prod.units

{'DATE': 'date',
 'WOPR:P1': 'stb/day',
 'WWPR:P1': 'stb/day',
 'WBHP:P1': 'psia',
 'WOPR:P2': 'sm3/day',
 'WWPR:P2': 'sm3/day',
 'WBHP:P2': 'barsa'}

In [19]:
sample_prod.wells

['P1', 'P2']

In [20]:
sample_prod.index.units

In [21]:
type(sample_prod)

SimDataFrame

In [22]:
sample_prod.set_index('DATE', inplace=True)
sample_prod

,WOPR:P1,WWPR:P1,WBHP:P1,WOPR:P2,WWPR:P2,WBHP:P2
,stb/day,stb/day,psia,sm3/day,sm3/day,barsa
DATE,,,,,,
2100-01-01,4872.000000,0.000000,5012.100000,536.000000,0.000000,245.070000
2100-01-08,4838.015086,12.707564,4987.600782,533.380024,2.619792,245.018541
2100-01-15,4804.267236,25.304309,4963.221317,530.772855,5.226413,244.967092
2100-01-22,4770.754795,37.791219,4938.961019,528.178429,7.819928,244.915655
2100-01-29,4737.476123,50.169277,4914.819305,525.596686,10.400402,244.864228
...,...,...,...,...,...,...
2106-12-03,389.264791,6782.302094,854.665589,91.398966,433.506733,227.178007
2106-12-10,386.549452,7096.137397,850.487971,90.952206,433.911970,227.130305
2106-12-17,383.853055,7443.580545,846.330773,90.507630,434.315018,227.082613
2106-12-24,381.175466,7830.322069,842.193896,90.065228,434.715890,227.034930
2106-12-31,378.516555,8263.413916,838.077240,89.624988,435.114595,226.987258

sample_prod = sample_prod.set_index('DATE')
sample_prod

In [23]:
sample_prod.index.units

'date'

# timely aggregation
**index _must_ be datetime**

## .daily()

In [ ]:
sample_prod.daily()

In [ ]:
sample_prod.daily(datetime_index=False)

In [ ]:
sample_prod.daily(complete_index=True)

In [ ]:
sample_prod.daily(datetime_index=False, complete_index=True)

## .monthly()

In [ ]:
sample_prod.monthly()

In [ ]:
sample_prod.monthly(datetime_index=True)

In [ ]:
sample_prod.monthly()

In [ ]:
sample_prod.monthly(complete_index=True)

In [ ]:
sample_prod.monthly(day='first')

In [ ]:
sample_prod.monthly(day='first', complete_index=True)

In [ ]:
sample_prod.monthly(complete_index=True)

In [ ]:
sample_prod.monthly(complete_index=True)

In [ ]:
sample_prod.monthly(complete_index=True, fillna_method='ffill')

## .yearly()

In [ ]:
sample_prod.yearly()

# get [ ]
## a single column name
### as SimSeries

In [ ]:
single_column = sample_prod['WOPR:P1']
single_column

### as SimDataFrame

In [ ]:
sample_prod[['WOPR:P1']]

## several columns by name

In [ ]:
sample_prod[['WOPR:P1', 'WOPR:P2']]

In [ ]:
sample_prod['WOPR:P1', 'WOPR:P2']

## columns by their _left_ or _right_ part of their names
semicolon **:** acts as name separator
- _left_**:**_right_

In [ ]:
sample_prod['WOPR']

In [ ]:
sample_prod['P1']

## slice of column names

In [ ]:
sample_prod['WWPR:P1':'WOPR:P2']

## name patterns
following **fnmatch** patterns

In [ ]:
sample_prod['W?PR*2']

In [ ]:
sample_prod['W?PR*']

## [ ] looks for its arguments in the columns and also in the index
When the argument is not found in the `.columns` names, it will look for the argument in the `.index` values.  
This shorcut is handy to takes advantage of DateTimeIndex capabilities!

In [ ]:
sample_prod['2100-04-09']

In [ ]:
sample_prod['2100-04']

In [ ]:
sample_prod['2100']

In [ ]:
sample_prod['2100-04-09':'2100-05-15']

## getting items from `SimSeries` instances

In [ ]:
from simpandas.common.daterelated import is_date_string, to_datetime

In [ ]:
to_datetime('2100-01-08') in single_column.index

In [ ]:
single_column['2100-01-08']

In [ ]:
single_column['2100-05']

In [ ]:
single_column['2100-04-30': '2100-06-12']

In [ ]:
single_column[['2100-01-08', '2100-02-19', '2100-05-07']]

## [_index_, _column_] 
Will behave as `.loc[_index_, _column_]` but **`.loc`** will be quicker:

In [ ]:
sample_prod['2100-02-26', 'P1']

In [ ]:
sample_prod['2100-04', 'P1']

In [ ]:
sample_prod['2100-04':'2100-06', 'P1']

In [ ]:
sample_prod['2100-02-26', 'WBHP:P1']

# Indexers
## .loc

In [ ]:
sample_prod.loc['2100-02-26']

In [ ]:
sample_prod.loc['2100-01']

In [ ]:
sample_prod.loc['2100']

In [ ]:
sample_prod.loc['2100-12-24':'2101-02']

In [ ]:
sample_prod.loc[:,'P1']

In [ ]:
sample_prod.loc['2100-12-24':'2101-01-15', 'P1']

In [ ]:
sample_prod.loc['2100-12-24':'2101-01-15', 'WBHP:P1': 'WWPR:P2']

In [ ]:
sample_prod.loc['2100-12-24', 'P1']

In [ ]:
sample_prod.loc['2100-12-24', 'WOPR:P1']

In [ ]:
sample_prod.loc['2100-12-24', 'WWPR:P1']

In [ ]:
sample_prod.loc['2100-02-26', 'WBHP:P1']

In [ ]:
sample_prod.loc[['2100-12-24', '2100-02-26']]

In [ ]:
sample_prod.units

## iloc

In [ ]:
sample_prod.iloc[0]

In [ ]:
sample_prod.iloc[0:5]

In [ ]:
sample_prod.iloc[0:5, 0:3]

In [ ]:
sample_prod.iloc[0:5, 0]

In [ ]:
sample_prod.iloc[:, 0]

In [ ]:
sample_prod.iloc[:, 0:3]

In [ ]:
sample_prod.iloc[1:7,[0, 4]]

# arithethic operations

In [ ]:
oil_rate1 = sample_prod[['WOPR:P1', 'WOPR:P2']]
oil_rate1

In [ ]:
oil_rate2 = sample_prod[['WOPR:P2', 'WOPR:P1']]
oil_rate2

In [ ]:
sample_prod['WOPR'].sum(axis=1)

In [ ]:
oil_rate1.sum(axis=1)

In [ ]:
oil_rate2.sum(axis=1)

In [ ]:
sample_prod['WOPR'].sum(axis=2)

In [ ]:
sample_prod['WOPR'].T.units

In [ ]:
sample_prod['WOPR'].sum(axis=0)

In [ ]:
sample_prod['WOPR'].sum(axis=0).T

In [ ]:
sample_prod['WOPR'].sum(axis=0).T.squeeze()

In [ ]:
p1_p2 = sample_prod['WOPR:P1'] + sample_prod['WOPR:P2']
p1_p2

# starting convertible validation

In [ ]:
import unyts

sample_prod['WOPR:P1'].to('sm3/day')

In [ ]:
unyts.convertible('stb/day', 'sm3/day')

# end convertible validation

In [ ]:
p1_p2 = sample_prod['WOPR:P1'] + sample_prod['WOPR:P2']
p1_p2

In [ ]:
unyts.convertible('stb/day', 'sm3/day')

In [ ]:
unyts.convert(1, 'stb/day', 'sm3/day')

In [ ]:
unyts.convertible('stb/day', 'sm3/day')

In [ ]:
p2_p1 = sample_prod['WOPR:P2'] + sample_prod['WOPR:P1']
p2_p1

In [ ]:
p2_p1 = sample_prod['WOPR:P2'] + sample_prod['WOPR:P1']
p2_p1

In [ ]:
p1_p2 == p2_p1

In [ ]:
p1_p2.eq(p2_p1)

In [ ]:
p1_p2.as_pandas().eq(p2_p1.as_pandas())

In [ ]:
p1_p2.eq(p2_p1, precision=2)

In [ ]:
p1_p2.eq2(p2_p1)

In [ ]:
p1_p2

In [ ]:
p2_p1

In [ ]:
p1_p2.round(2) == p2_p1.to('stb/day').round(2)

In [ ]:
p1_p2.round(2)

In [ ]:
sample_prod['WOPR:P1'].sum()

In [ ]:
sample_prod['WOPR:P1'].mean()

In [ ]:
sample_prod['WOPR:P1'].std()

In [ ]:
sample_prod['WOPR:P1'].var()

In [ ]:
sample_prod['WOPR:P1'].prod()

In [ ]:
sample_prod['WOPR:P1'].rms()

In [ ]:
test = sample_prod['WOPR:P1'].copy()
test

In [ ]:
test['the_end'] = 0

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A':[1,2,3], 'B': [0.1, 0.2, 0.3]})
df2 = pd.DataFrame({'B': [0.1, 0.2, 0.3], 'A':[1,2,3], 'C':[0, 0, 0]})

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df2 + df1

In [ ]:
test

In [ ]:
test.units

In [ ]:
test['the_end'] = 10, 'sm3/day'

In [ ]:
test.units

In [ ]:
test

In [ ]:
test = spd.SimSeries(data=[1,2,3,4], units={'A':'m', 'B':'in', 'C':'cc', 'D':'s'}, index=list('ABCD'), name='testing')
test

In [ ]:
test + test

In [ ]:
uno = test.as_simdataframe().df.iloc[:,0]
uno

In [ ]:
uno.name

In [ ]:
test.params_

In [ ]:
test.units

In [ ]:
sample_prod[['WOPR:P1']] + sample_prod[['WOPR:P2']]

In [ ]:
sample_prod[['WOPR:P2']] + sample_prod[['WOPR:P1']]

In [ ]:
sample_prod[['WOPR:P1']] + sample_prod[['WWPR:P1']]

In [ ]:
sample_prod['WOPR:P2'] + sample_prod['WOPR:P1']

In [ ]:
sample_prod[['WOPR:P2']] + sample_prod[['WOPR:P1']]

In [ ]:
sample_prod

In [ ]:
sample_prod[['P2']]

In [ ]:
sample_prod[['P1']]

In [ ]:
sample_prod[['P1']] + sample_prod[['P2']]

In [ ]:
sample_prod[['P1']] - sample_prod[['P2']]

In [ ]:
sample_prod[['P1']] / sample_prod[['P2']]

In [ ]:
sample_prod[['P1']] * sample_prod[['P2']]

In [ ]:
sp1, sp2, com = sample_prod[['P1']]._common_rename(sample_prod[['P2']])

In [ ]:
sp1['WOPR'] == sp2['WOPR']

In [ ]:
sp1[['WOPR']] < sp2[['WOPR']]

In [ ]:
sample_prod[['P1']] == sample_prod[['P2']]

In [ ]:
sample_prod[['P1']] < sample_prod[['P2']]